---
- name: Add grafana group
  ansible.builtin.group:
    name: grafana
    system: true
  
- name: Add grafana user
  ansible.builtin.user:
    name: grafana
    system: true
    shell: /bin/false
    home: /usr/share/grafana

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: grafana
  loop:
    - /etc/grafana

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: /etc/grafana/grafana.key
    owner: grafana
    group: grafana

- name: Generate a CSR
  community.crypto.openssl_csr:
    path: /etc/grafana/grafana.csr
    owner: grafana
    group: grafana
    privatekey_path: /etc/grafana/grafana.key
    common_name: "{{ ansible_hostname }}"
    subject_alt_name: "DNS:localhost,DNS:{{ ansible_hostname }},IP:{{ ansible_enp0s8.ipv4.address }}"

- name: Sign certificate with CA
  community.crypto.x509_certificate:
    path: /etc/grafana/grafana.crt
    owner: grafana
    group: grafana
    csr_path: /etc/grafana/grafana.csr
    ownca_content: "{{lookup('file', 'files/pawapay-assignment-ca.crt') }}"
    ownca_privatekey_content: "{{lookup('file', 'files/pawapay-assignment-ca.key') }}"
    provider: ownca

- name: Copy CA certificate
  ansible.builtin.copy:
    src: pawapay-assignment-ca.crt
    dest: /etc/grafana/ca.crt
    owner: grafana
    group: grafana
