---
# logstash variables
logstash_version: '7.x'
logstash_package: logstash=1:7.15.1-1
logstash_elasticsearch_hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_enp0s8', 'ipv4', 'address']) | map('regex_replace', '^(.*)$','http://\\1:9200') | join(',') }}"
logstash_install_plugins:
  - logstash-input-beats
